### PR TITLE
ENH: adds midpoint_root method

### PR DESCRIPTION
**Pull request by gregcaporaso**
addresses #4

### CODE REVIEW

**Comment by gregcaporaso** [comment]
@rob-knight, are you available to review this one? we'll review tomorrow on my end if not.

**Comment by rob-knight** [comment]
doing it now

On Aug 25, 2016, at 4:52 PM, Greg Caporaso <notifications@github.com<mailto:notifications@github.com>> wrote:


@rob-knight<https://github.com/rob-knight>, are you available to review this one? we'll review tomorrow on my end if not.

**Comment by rob-knight** [comment]
Looks good!

**Comment by gregcaporaso** [comment]
Thanks @rob-knight!

**Pull request merged**
