### PR TITLE
iqtree associated actions to be deprecated in q2-phylogeny

### PR DESCRIPTION
**Pull request by mikerobeson**
Existing [IQ-TREE 2](http://www.iqtree.org/) functionality is in the process of being transferred from [q2-phylogeny](https://github.com/qiime2/q2-phylogeny) to [q2-iqtree2](https://github.com/mikerobeson/q2-iqtree2).

This PR simply sets `deprecated=True` to the following actions within `q2-phylogeny`:
- `iqtree`
- `iqtree-ultrafast-bootstrap`
- `align-to-tree-mafft-iqtree`

### CODE REVIEW

**Comment by thermokarst** [comment]
Hi @mikerobeson! Sorry for the slow response here - looks like something might've gone wrong with the branch here, the "Files changed" tab is empty... Let me know if you want a hand poking around at things, happy to help!

**Comment by mikerobeson** [comment]
Weird! Not sure what happened. I'll try and fix it.

**Comment by mikerobeson** [comment]
@thermokarst,  looks like I got it working. Should only be the 1 file `q2_phylogeny/plugin_setup.py`.

**Review by thermokarst — APPROVED** [review]
Thanks @mikerobeson!

**Pull request merged**
